  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    network_mode: host
    user: "0"
    privileged: true
    env_file: ./services/nodered/nodered.env
    ports:
      - 1880:1880
    volumes:
      - ./volumes/nodered/data:/data
